# Generated by Django 4.2.5 on 2023-10-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('number', models.IntegerField()),
                ('male', models.CharField(max_length=250)),
                ('female', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('parent_selection', models.CharField(max_length=250)),
                ('child_selection', models.CharField(max_length=250)),
                ('savingaccount', models.CharField(max_length=250)),
                ('currentaccount', models.CharField(max_length=250)),
                ('joinaccount', models.CharField(max_length=250)),
                ('demataccount', models.CharField(max_length=250)),
                ('debitcard', models.CharField(max_length=250)),
                ('creditcard', models.CharField(max_length=250)),
                ('chequebook', models.CharField(max_length=250)),
            ],
        ),
    ]
